### PR TITLE
Port to wrap the new elm 0.19 tooling

### LINKED ISSUE #35: Doesn't work on 0.19
`elm-make` is gone, replaced with just a single `elm` binary.

As a shim, installing this shell script as `elm-make` technically makes it works:

```bash
#!/bin/bash
shift  # swallow --yes, its gone
[[ "$@" ]] && exec node_modules/.bin/elm make "$@"
```

### PR DESCRIPTION
**Pull request by vodik**
Resolves #35 by boldly dropping backwards compatibility. Not sure if its desirable, but at least this works and my shim can be dropped.

The init step is also gone, its no longer necessary. `elm make` automatically fetches dependencies without prompting. Also added is the new `--optimize` flag for the new minifier include.

Didn't touch documentation or tests as I'm not sure if this approach is palatable - but at least it works in the meanwhile.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -11,40 +11,37 @@ var PluginError   = require('plugin-error')
...
   if(!!options){
-    var yes = options.yesToAllPrompts;
-    if(yes !== undefined && !yes) {
-      args = [];
-    }
-
-    if(options.elmMake) { exe = options.elmMake; }
+    if(options.elm) { exe = options.elm; }
 
     if(options.warn === true) { args = args.concat(['--warn']); }
```
Comment (bdukes) [inline index.js]: `--warn` is not currently supported in 0.19 (though Evan said it may be added back, so maybe we just leave it in…)

File: index.js [hunk 2]
```diff
@@ -144,7 +128,7 @@ function compileHandler(opts, file) {
         , args = opts.args.concat(state.input, '--output', state.tmpOut);
       state.output = path.resolve(process.cwd(), path.basename(file.path, path.extname(file.path)) + opts.ext);
       compile(state.exe, args, opts.spawn, function(err, warnings){
-        if(!!err) { deferred.reject({state: state, message: err}); }
+        if(!!err) { deferred.reject({state: state, message: warnings}); }
```
Comment (bdukes) [inline index.js]: It seems like this would be losing error information, is that not the case?
